0: good
1: Atelectasis
2: Cardiomegaly
3: Effusion
4: Infiltration
5: Mass
6: Nodule
7: Pneumonia
8: Pneumothorax
9: Consolidation
10: Edema
11: Emphysema
12: Fibrosis
13: Pleural_Thickening
14: Hernia
15: Parenchyma
16: Kidney
17: Parenchyma0025
18: Parenchyma2550
19: Parenchyma5075
20: Parenchyma7510
21: PneumoniaVirus
22: PneumoniaBacteria
23: Tumor
24: Glioma
25: Meningioma
26: Pituitary
27: Tuberculosis
28: Lungs
29: Brain
30: Kidneys
31: Bladder
32: Bone
33: Liver
34: angiomyolipoma
35: chromophobe
36: clearcellpapillaryrcc
37: clearcellrcc
38: mest
39: multilocularcysticrcc
40: oncocytoma
41: papillary
42: rcc unclassified
43: spindlecell neoplasm
44: urothelial
45: wilms