Stanford_COCA:
  import_statement: "from src.pipelines.ct.stanford_coca import preprocess_coca"
  function_name: "preprocess_coca"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
Stanford_Brain_MET:
  import_statement: "from src.pipelines.mri.stanford_brain_met import preprocess_stanford_brain_met"
  function_name: "preprocess_stanford_brain_met"
  args:
    source_path: ""
    target_path: "./data/"
Alzheimers_Dataset:
  import_statement: "from src.pipelines.mri.alzheimers import preprocess_alzheimers"
  function_name: "preprocess_alzheimers"
  args:
    source_path: ""
    target_path: "./data/"
