CoronaHack_Chest_X-Ray_Dataset:
  import_statement: "from src.pipelines.xray.coronahack_chest_xray import preprocess_coronahack_chest_xray"
  function_name: "preprocess_coronahack_chest_xray"
  args:
    source_path: ""
    target_path: "./data/"
Stanford_Brain_MET:
  import_statement: "from src.pipelines.mri.stanford_brain_met import preprocess_stanford_brain_met"
  function_name: "preprocess_stanford_brain_met"
  args:
    source_path: ""
    target_path: "./data/"
Stanford_COCA:
  import_statement: "from src.pipelines.ct.stanford_coca import preprocess_coca"
  function_name: "preprocess_coca"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
