Stanford_COCA:
  import_statement: "from src.pipelines.ct.stanford_coca import preprocess_coca"
  function_name: "preprocess_coca"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
Stanford_Brain_MET:
  import_statement: "from src.pipelines.mri.stanford_brain_met import preprocess_stanford_brain_met"
  function_name: "preprocess_stanford_brain_met"
  args:
    source_path: ""
    target_path: "./data/"
Brain_Tumor_Detection:
  import_statement: "from src.pipelines.mri.brain_tumor_detection import preprocess_brain_tumor_detection"
  function_name: "preprocess_brain_tumor_detection"
  args:
    source_path: ""
    target_path: "./data/"
