Stanford_COCA:
  import_statement: "from src.pipelines.ct.stanford_coca import preprocess_coca"
  function_name: "preprocess_coca"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
Stanford_Brain_MET:
  import_statement: "from src.pipelines.mri.stanford_brain_met import preprocess_stanford_brain_met"
  function_name: "preprocess_stanford_brain_met"
  args:
    source_path: ""
    target_path: "./data/"
Brain_With_Hemorrhage:
  import_statement: "from src.pipelines.ct.brain_with_hemorrhage import preprocess_brain_with_hemorrhage"
  function_name: "preprocess_brain_with_hemorrhage"
  args:
    source_path: "/Users/piotr/Desktop/UMIE/data/computed-tomography-images-for-intracranial-hemorrhage-detection-and-segmentation-1.0.0/Patients_CT"
    target_path: "/Users/piotr/Desktop/UMIE/processed_data"
    masks_path: "/Users/piotr/Desktop/UMIE/data/computed-tomography-images-for-intracranial-hemorrhage-detection-and-segmentation-1.0.0/Patients_CT"
