Stanford_COCA:
  import_statement: "from src.pipelines.ct.stanford_coca import preprocess_coca"
  function_name: "preprocess_coca"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
Stanford_Brain_MET:
  import_statement: "from src.pipelines.mri.stanford_brain_met import preprocess_stanford_brain_met"
  function_name: "preprocess_stanford_brain_met"
  args:
    source_path: ""
    target_path: "./data/"
Finding_and_Measuring_Lungs_in_CT_Data:
  import_statement: "from src.pipelines.ct.finding_and_measuring_lungs_in_ct import preprocess_lungs_ct"
  function_name: "preprocess_lungs_ct"
  args:
    source_path: ""
    target_path: "./data/"
    masks_path: ""
