# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
    - run: poetry --version

    - name: Install Poetry dependecies
      run: poetry install

    - name: Run pytest tests
      run: poetry run pytest testing/tests
